server:
  port: 8081

spring:
  # 接口加解密配置
  encrypt:
    # 是否启用
    enable: true
    # 内部调用请求头，示例：inner=yes，当请求头包含inner，并且其值为yes时，不做加解密处理
    internal-header: inner=yes
    # 加解密算法，支持AES、DES、RSA、SM2、SM4，支持自定义算法，需要实现Decoder、Encipher
    algorithm: aes
    # 自定义解密器
    decoder:
    # 自定义加密器
    encipher:
    # 公钥
    public-key:
    # 私钥
    private-key: aEsva0zDHECg47P8SuPzmw==
    # 忽略请求参数解密接口
    ignore-request-decrypt-paths:
    # 忽略响应结果加密接口
    ignore-response-encrypt-paths:
    # appId请求头名称，提供给第三方调用接口时，根据此请求头值获取接口加解密配置，需实现EncryptConfigService接口
    app-id-header-name: app-id
    # url密文参数名称
    url-parameter-name: en
    # 请求body密文参数名称
    body-parameter-name: data
